apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "petclinic.fullname" .}}
data:
  MYSQL_ROOT_PASSWORD:
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  MYSQL_USER: petclinic 
  MYSQL_PASSWORD: petclinic 
  MYSQL_DATABASE: petclinic